spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google.client_id}
            client-secret: ${google.client_secret}
#            scope:
#              - openid
#              - email
#              - profile
#            redirect-uri: http://localhost:8080/login/oauth2/code/google
#        provider:
#          google:
#            authorization-uri: https://accounts.google.com/o/oauth2/auth
#            token-uri: https://accounts.google.com/o/oauth2/token
#            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
#            user-name-attribute: name