spring:
  datasource:
    url: jdbc:h2:file:./src/main/resources/db/apidb
    driver-class-name: org.h2.Driver
    username: sa
    password: sa2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update