name: Semantic Versioning for Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  bump_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Determine Current Version
        id: version
        run: |
          current_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          new_version=$(echo $current_version | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
          echo "::set-output name=current_version::$current_version"
          echo "::set-output name=new_version::$new_version"

      - name: Bump Version
        run: |
          mvn versions:set -DnewVersion=$NEW_VERSION

      - name: Commit and Push Version Update
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git commit -am "Bump version to $NEW_VERSION"
          git push origin master
